[build]
  publish = "public"
  command = "echo \"window.SUPABASE_URL='$VITE_SUPABASE_URL'; window.SUPABASE_ANON_KEY='$VITE_SUPABASE_ANON_KEY';\" > public/config.js"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
